services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel-php
        volumes:
            - .:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:1.25
        container_name: laravel-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

    node:
        image: node:20
        container_name: laravel-node
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: bash -c "npm install && npm run build"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    db_data:
