name: Build and Push Docker Image with Smart Versioning

on:
  push:
    branches:
      - aplikasi_ppdb_docker

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Determine version
        id: version
        run: |
          # Ambil tag terakhir dari git
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "LAST_TAG=$LAST_TAG"

          # Pisahkan major.minor.patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "${LAST_TAG#v}"

          # Cek commit message terakhir
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit message: $COMMIT_MSG"

          if [[ "$COMMIT_MSG" == *"[major]"* ]]; then
            MAJOR=$((MAJOR+1))
            MINOR=0
            PATCH=0
          elif [[ "$COMMIT_MSG" == *"[minor]"* ]]; then
            MINOR=$((MINOR+1))
            PATCH=0
          else
            PATCH=$((PATCH+1))
          fi

          NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          echo "New tag: $NEW_TAG"

          # Set environment variable untuk steps berikut
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            riskiputraalamzah/aplikasi_ppdb:latest
            riskiputraalamzah/aplikasi_ppdb:${{ env.new_tag }}

      - name: Create Git tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
